/** Font Awesome 5 类名 → Font Awesome 6（Iconify）名称 */
export const FA5_ALIASES = {
  search: 'magnifying-glass',
  'external-link-alt': 'up-right-from-square',
  'sign-in-alt': 'right-to-bracket',
  'sign-out-alt': 'right-from-bracket',
  'sign-out': 'right-from-bracket',
  times: 'xmark',
  history: 'clock-rotate-left',
  'fire-alt': 'fire-flame-curved',
  'compress-alt': 'down-left-and-up-right-to-center',
  'align-left': 'align-left',
  'trash-alt': 'trash-can',
  'file-code': 'file-code',
  'file-alt': 'file-lines',
  'file-image': 'file-image',
  'file-pdf': 'file-pdf',
  'file-excel': 'file-excel',
  'file-word': 'file-word',
  'folder-open': 'folder-open',
  'folder-plus': 'folder-plus',
  'level-up-alt': 'turn-up',
  'cloud-upload-alt': 'cloud-arrow-up',
  'sync-alt': 'arrows-rotate',
  'redo': 'arrow-rotate-right',
  'random': 'shuffle',
  'expand': 'expand',
  'clone': 'clone',
  'hand-holding-usd': 'hand-holding-dollar',
  'money-bill': 'money-bill-1',
  'sliders-h': 'sliders',
  'quote-left': 'quote-left',
  'user-edit': 'user-pen',
  'id-card': 'id-card',
  'info-circle': 'circle-info',
  'question-circle': 'circle-question',
  'exclamation-circle': 'circle-exclamation',
  'exclamation-triangle': 'triangle-exclamation',
  'check-circle': 'circle-check',
  'plus-circle': 'circle-plus',
  'globe-americas': 'earth-americas',
  'chart-area': 'chart-area',
  'chart-pie': 'chart-pie',
  'chart-line': 'chart-line',
  'gas-pump': 'gas-pump',
  'caret-up': 'caret-up',
  'caret-down': 'caret-down',
  'ellipsis-v': 'ellipsis-vertical',
  'ellipsis-h': 'ellipsis',
  'volume-up': 'volume-high',
  'volume-down': 'volume-low',
  'volume-mute': 'volume-xmark',
  'tachometer-alt': 'gauge-high',
  'github-alt': 'github',
  'menu-down': 'caret-down',
  'menu-up': 'caret-up',
  'share-alt': 'share-nodes',
  'shield-alt': 'shield-halved',
  'user-plus': 'user-plus',
  'pen': 'pen',
  usps: 'envelope',
  columns: 'table-columns',
  'th-large': 'table-cells-large',
  'users-cog': 'users-gear',
  heartbeat: 'heart-pulse',
  gamepad: 'gamepad',
  home: 'house',
}

export function resolveFaIconName(name) {
  if (!name) return ''
  const raw = String(name).replace(/^fa-/, '')
  return FA5_ALIASES[raw] || raw
}
